-- Address decode logic for ipbus fabric
-- 
-- This file has been AUTOGENERATED from the address table - do not hand edit
-- 
-- We assume the synthesis tool is clever enough to recognise exclusive conditions
-- in the if statement.
-- 
-- Dave Newbold, February 2011

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_global is

  constant IPBUS_SEL_WIDTH: positive := 5; -- Should be enough for now?
  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_global(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically  generated VHDL the Sat Apr 15 21:05:15 2017 
  constant N_SLV_VERSION: integer := 0;
  constant N_SLV_SEL: integer := 1;
  constant N_SLV_CSR: integer := 2;
  constant N_SLV_TSTAMP: integer := 3;
  constant N_SLV_SPILL_CTR: integer := 4;
  constant N_SLAVES: integer := 5;
-- END automatically generated VHDL

    
end ipbus_decode_global;

package body ipbus_decode_global is

  function ipbus_sel_global(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically  generated VHDL the Sat Apr 15 21:05:15 2017 
    if    std_match(addr, "-----------------------------000") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_VERSION, IPBUS_SEL_WIDTH)); -- version / base 0x00000000 / mask 0x00000007
    elsif std_match(addr, "-----------------------------001") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_SEL, IPBUS_SEL_WIDTH)); -- sel / base 0x00000001 / mask 0x00000007
    elsif std_match(addr, "-----------------------------01-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_CSR, IPBUS_SEL_WIDTH)); -- csr / base 0x00000002 / mask 0x00000006
    elsif std_match(addr, "-----------------------------10-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_TSTAMP, IPBUS_SEL_WIDTH)); -- tstamp / base 0x00000004 / mask 0x00000006
    elsif std_match(addr, "-----------------------------110") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_SPILL_CTR, IPBUS_SEL_WIDTH)); -- spill_ctr / base 0x00000006 / mask 0x00000007
-- END automatically generated VHDL

    else
        sel := ipbus_sel_t(to_unsigned(N_SLAVES, IPBUS_SEL_WIDTH));
    end if;

    return sel;

  end function ipbus_sel_global;

end ipbus_decode_global;

