-- Address decode logic for ipbus fabric
-- 
-- This file has been AUTOGENERATED from the address table - do not hand edit
-- 
-- We assume the synthesis tool is clever enough to recognise exclusive conditions
-- in the if statement.
-- 
-- Dave Newbold, February 2011

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_master is

  constant IPBUS_SEL_WIDTH: positive := 5; -- Should be enough for now?
  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_master(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically  generated VHDL the Fri Sep  1 09:50:35 2017 
  constant N_SLV_GLOBAL: integer := 0;
  constant N_SLV_SPILL: integer := 1;
  constant N_SLV_TSTAMP: integer := 2;
  constant N_SLV_SCMD_GEN: integer := 3;
  constant N_SLV_PARTITION: integer := 4;
  constant N_SLAVES: integer := 5;
-- END automatically generated VHDL

    
end ipbus_decode_master;

package body ipbus_decode_master is

  function ipbus_sel_master(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically  generated VHDL the Fri Sep  1 09:50:35 2017 
    if    std_match(addr, "-----------------------0-0--00--") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_GLOBAL, IPBUS_SEL_WIDTH)); -- global / base 0x00000000 / mask 0x0000014c
    elsif std_match(addr, "-----------------------0-0--10--") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_SPILL, IPBUS_SEL_WIDTH)); -- spill / base 0x00000008 / mask 0x0000014c
    elsif std_match(addr, "-----------------------0-0--11--") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_TSTAMP, IPBUS_SEL_WIDTH)); -- tstamp / base 0x0000000c / mask 0x0000014c
    elsif std_match(addr, "-----------------------0-1------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_SCMD_GEN, IPBUS_SEL_WIDTH)); -- scmd_gen / base 0x00000040 / mask 0x00000140
    elsif std_match(addr, "-----------------------1-0------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_PARTITION, IPBUS_SEL_WIDTH)); -- partition / base 0x00000100 / mask 0x00000140
-- END automatically generated VHDL

    else
        sel := ipbus_sel_t(to_unsigned(N_SLAVES, IPBUS_SEL_WIDTH));
    end if;

    return sel;

  end function ipbus_sel_master;

end ipbus_decode_master;

